[package]
name = "lson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
home = "0.5.9"
serde = "1.0.197"
serde_json = "1.0.114"
